# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spacex_api/device/services/unlock/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spacex_api/device/services/unlock/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/spacex_api/device/services/unlock/service.proto\x12!SpaceX.API.Device.Services.Unlock\"\xa2\x01\n\x0fUnlockChallenge\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05nonce\x18\x02 \x01(\x0c\x12\x11\n\tsign_spki\x18\x04 \x01(\x0c\x12\x15\n\rgrant_keydata\x18\x05 \x01(\t\x12\x17\n\x0fservice_keydata\x18\x06 \x01(\t\x12\x18\n\x10\x61uthority_grants\x18\x07 \x03(\tJ\x04\x08\x03\x10\x04R\ngrant_spki\"\x14\n\x12StartUnlockRequest\"J\n\x13StartUnlockResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05nonce\x18\x02 \x01(\x0c\x12\x11\n\tsign_spki\x18\x03 \x01(\x0c\";\n\x13\x46inishUnlockRequest\x12\x11\n\tchallenge\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"&\n\x14\x46inishUnlockResponse\x12\x0e\n\x06status\x18\x01 \x01(\r2\x93\x02\n\rUnlockService\x12~\n\x0bStartUnlock\x12\x35.SpaceX.API.Device.Services.Unlock.StartUnlockRequest\x1a\x36.SpaceX.API.Device.Services.Unlock.StartUnlockResponse\"\x00\x12\x81\x01\n\x0c\x46inishUnlock\x12\x36.SpaceX.API.Device.Services.Unlock.FinishUnlockRequest\x1a\x37.SpaceX.API.Device.Services.Unlock.FinishUnlockResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacex_api.device.services.unlock.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNLOCKCHALLENGE']._serialized_start=87
  _globals['_UNLOCKCHALLENGE']._serialized_end=249
  _globals['_STARTUNLOCKREQUEST']._serialized_start=251
  _globals['_STARTUNLOCKREQUEST']._serialized_end=271
  _globals['_STARTUNLOCKRESPONSE']._serialized_start=273
  _globals['_STARTUNLOCKRESPONSE']._serialized_end=347
  _globals['_FINISHUNLOCKREQUEST']._serialized_start=349
  _globals['_FINISHUNLOCKREQUEST']._serialized_end=408
  _globals['_FINISHUNLOCKRESPONSE']._serialized_start=410
  _globals['_FINISHUNLOCKRESPONSE']._serialized_end=448
  _globals['_UNLOCKSERVICE']._serialized_start=451
  _globals['_UNLOCKSERVICE']._serialized_end=726
# @@protoc_insertion_point(module_scope)
