# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spacex_api/telemetron/public/common/time.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spacex_api/telemetron/public/common/time.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.spacex_api/telemetron/public/common/time.proto\x12#SpaceX.API.Telemetron.Public.Common\"_\n\rTimestampInfo\x12\x39\n\x05\x65poch\x18\x01 \x01(\x0e\x32*.SpaceX.API.Telemetron.Public.Common.Epoch\x12\x13\n\x0bnanoseconds\x18\x02 \x01(\x03*\x1a\n\x05\x45poch\x12\x08\n\x04UNIX\x10\x00\x12\x07\n\x03GPS\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacex_api.telemetron.public.common.time_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EPOCH']._serialized_start=184
  _globals['_EPOCH']._serialized_end=210
  _globals['_TIMESTAMPINFO']._serialized_start=87
  _globals['_TIMESTAMPINFO']._serialized_end=182
# @@protoc_insertion_point(module_scope)
