# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spacex_api/device/account_shard.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spacex_api/device/account_shard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%spacex_api/device/account_shard.proto\x12\x11SpaceX.API.Device*{\n\x0c\x41\x63\x63ountShard\x12\x19\n\x15\x41\x43\x43OUNT_SHARD_UNKNOWN\x10\x00\x12\x19\n\x15\x41\x43\x43OUNT_SHARD_DEFAULT\x10\x01\x12\x17\n\x13\x41\x43\x43OUNT_SHARD_INDIA\x10\x02\x12\x1c\n\x18\x41\x43\x43OUNT_SHARD_STARSHIELD\x10\x03\x42%Z#spacex.com/api/device/account_shardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacex_api.device.account_shard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#spacex.com/api/device/account_shard'
  _globals['_ACCOUNTSHARD']._serialized_start=60
  _globals['_ACCOUNTSHARD']._serialized_end=183
# @@protoc_insertion_point(module_scope)
