# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spacex_api/device/dish_config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spacex_api/device/dish_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#spacex_api/device/dish_config.proto\x12\x11SpaceX.API.Device\"\x94\x07\n\nDishConfig\x12\x42\n\x0esnow_melt_mode\x18\x01 \x01(\x0e\x32*.SpaceX.API.Device.DishConfig.SnowMeltMode\x12\x1d\n\x14\x61pply_snow_melt_mode\x18\xe9\x07 \x01(\x08\x12P\n\x15location_request_mode\x18\x02 \x01(\x0e\x32\x31.SpaceX.API.Device.DishConfig.LocationRequestMode\x12$\n\x1b\x61pply_location_request_mode\x18\xd1\x0f \x01(\x08\x12\x44\n\x0flevel_dish_mode\x18\x03 \x01(\x0e\x32+.SpaceX.API.Device.DishConfig.LevelDishMode\x12\x1e\n\x15\x61pply_level_dish_mode\x18\xb9\x17 \x01(\x08\x12 \n\x18power_save_start_minutes\x18\x04 \x01(\r\x12\'\n\x1e\x61pply_power_save_start_minutes\x18\xa1\x1f \x01(\x08\x12#\n\x1bpower_save_duration_minutes\x18\x05 \x01(\r\x12*\n!apply_power_save_duration_minutes\x18\x89\' \x01(\x08\x12\x17\n\x0fpower_save_mode\x18\x06 \x01(\x08\x12\x1e\n\x15\x61pply_power_save_mode\x18\xf1. \x01(\x08\x12\x1c\n\x14swupdate_reboot_hour\x18\t \x01(\r\x12#\n\x1a\x61pply_swupdate_reboot_hour\x18\xa9\x46 \x01(\x08\x12+\n#swupdate_three_day_deferral_enabled\x18\x07 \x01(\x08\x12\x32\n)apply_swupdate_three_day_deferral_enabled\x18\xd9\x36 \x01(\x08\x12\x13\n\x0b\x61sset_class\x18\x08 \x01(\r\x12\x1a\n\x11\x61pply_asset_class\x18\xc1> \x01(\x08\"7\n\x0cSnowMeltMode\x12\x08\n\x04\x41UTO\x10\x00\x12\r\n\tALWAYS_ON\x10\x01\x12\x0e\n\nALWAYS_OFF\x10\x02\"*\n\x13LocationRequestMode\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05LOCAL\x10\x01\"6\n\rLevelDishMode\x12\x14\n\x10TILT_LIKE_NORMAL\x10\x00\x12\x0f\n\x0b\x46ORCE_LEVEL\x10\x01\x42\x17Z\x15spacex.com/api/deviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacex_api.device.dish_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025spacex.com/api/device'
  _globals['_DISHCONFIG']._serialized_start=59
  _globals['_DISHCONFIG']._serialized_end=975
  _globals['_DISHCONFIG_SNOWMELTMODE']._serialized_start=820
  _globals['_DISHCONFIG_SNOWMELTMODE']._serialized_end=875
  _globals['_DISHCONFIG_LOCATIONREQUESTMODE']._serialized_start=877
  _globals['_DISHCONFIG_LOCATIONREQUESTMODE']._serialized_end=919
  _globals['_DISHCONFIG_LEVELDISHMODE']._serialized_start=921
  _globals['_DISHCONFIG_LEVELDISHMODE']._serialized_end=975
# @@protoc_insertion_point(module_scope)
