# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spacex_api/device/rssi_scan.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spacex_api/device/rssi_scan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!spacex_api/device/rssi_scan.proto\x12\x11SpaceX.API.Device\"b\n\tRssiEntry\x12\x14\n\x0ctheta_degree\x18\x01 \x01(\x01\x12\x12\n\nphi_degree\x18\x02 \x01(\x01\x12\x10\n\x08rssi_dbf\x18\x03 \x01(\x01\x12\x19\n\x11scan_timestamp_ms\x18\x04 \x01(\x04\"\'\n\x14\x44ishActivateRssiScan\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\r\"\xa4\x01\n\x15\x44ishGetRssiScanResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\r\x12\x19\n\x11request_timestamp\x18\x03 \x01(\x04\x12\x16\n\x0enumber_samples\x18\x04 \x01(\r\x12\x36\n\x10rssi_scan_points\x18\x05 \x03(\x0b\x32\x1c.SpaceX.API.Device.RssiEntryB\x17Z\x15spacex.com/api/deviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacex_api.device.rssi_scan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025spacex.com/api/device'
  _globals['_RSSIENTRY']._serialized_start=56
  _globals['_RSSIENTRY']._serialized_end=154
  _globals['_DISHACTIVATERSSISCAN']._serialized_start=156
  _globals['_DISHACTIVATERSSISCAN']._serialized_end=195
  _globals['_DISHGETRSSISCANRESULT']._serialized_start=198
  _globals['_DISHGETRSSISCANRESULT']._serialized_end=362
# @@protoc_insertion_point(module_scope)
