/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "ground_station.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(groundstation_RocketLoRaSample, groundstation_RocketLoRaSample, AUTO)


PB_BIND(groundstation_Lora1Rf69Packet, groundstation_Lora1Rf69Packet, 2)


PB_BIND(groundstation_AntennaState, groundstation_AntennaState, AUTO)


PB_BIND(groundstation_GroundImu, groundstation_GroundImu, AUTO)


PB_BIND(groundstation_AhrsStatus, groundstation_AhrsStatus, AUTO)


PB_BIND(groundstation_RawImuSample, groundstation_RawImuSample, AUTO)


PB_BIND(groundstation_RawMagSample, groundstation_RawMagSample, AUTO)


PB_BIND(groundstation_RawYawImuSample, groundstation_RawYawImuSample, AUTO)


PB_BIND(groundstation_RawSensorsCommand, groundstation_RawSensorsCommand, AUTO)


PB_BIND(groundstation_AxisCommand, groundstation_AxisCommand, AUTO)


PB_BIND(groundstation_JogCommand, groundstation_JogCommand, AUTO)


PB_BIND(groundstation_DeclinationCommand, groundstation_DeclinationCommand, AUTO)


PB_BIND(groundstation_StarlinkProxyStatus, groundstation_StarlinkProxyStatus, 2)







#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

