/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GROUNDSTATION_GROUND_STATION_PB_H_INCLUDED
#define PB_GROUNDSTATION_GROUND_STATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _groundstation_FlightState {
    groundstation_FlightState_FLIGHT_STATE_GROUND_IDLE = 0,
    groundstation_FlightState_FLIGHT_STATE_ARMED = 1,
    groundstation_FlightState_FLIGHT_STATE_POWERED_ASCENT = 2,
    groundstation_FlightState_FLIGHT_STATE_COAST_ASCENT = 3,
    groundstation_FlightState_FLIGHT_STATE_APOGEE = 4,
    groundstation_FlightState_FLIGHT_STATE_DESCENT_DROGUE = 5,
    groundstation_FlightState_FLIGHT_STATE_DESCENT_MAIN = 6,
    groundstation_FlightState_FLIGHT_STATE_LANDED = 7,
    groundstation_FlightState_FLIGHT_STATE_FAULT = 255
} groundstation_FlightState;

typedef enum _groundstation_JogAxis {
    groundstation_JogAxis_JOG_AXIS_UNSPECIFIED = 0,
    groundstation_JogAxis_JOG_AXIS_AZ = 1,
    groundstation_JogAxis_JOG_AXIS_EL = 2
} groundstation_JogAxis;

typedef enum _groundstation_TrackerMode {
    groundstation_TrackerMode_TRACKER_MODE_STOP = 0,
    groundstation_TrackerMode_TRACKER_MODE_MANUAL = 1,
    groundstation_TrackerMode_TRACKER_MODE_AUTO = 2,
    groundstation_TrackerMode_TRACKER_MODE_SCAN = 3,
    groundstation_TrackerMode_TRACKER_MODE_SERVOTEST = 4,
    groundstation_TrackerMode_TRACKER_MODE_FAULT = 5
} groundstation_TrackerMode;

typedef enum _groundstation_CalibrationAction {
    groundstation_CalibrationAction_CAL_ACTION_UNSPECIFIED = 0,
    groundstation_CalibrationAction_CAL_ACTION_BEGIN_GUIDED = 1,
    groundstation_CalibrationAction_CAL_ACTION_SET_AZ_REFERENCE = 2,
    groundstation_CalibrationAction_CAL_ACTION_SET_EL_REFERENCE = 3,
    groundstation_CalibrationAction_CAL_ACTION_CLEAR = 4,
    groundstation_CalibrationAction_CAL_ACTION_ENABLE_TRACKING = 5
} groundstation_CalibrationAction;

/* Struct definitions */
typedef struct _groundstation_RocketLoRaSample {
    bool has_boot_ms;
    uint32_t boot_ms;
    bool has_state;
    groundstation_FlightState state;
    bool has_sats;
    uint32_t sats;
    bool has_flags;
    uint32_t flags;
    bool has_lat;
    double lat;
    bool has_lon;
    double lon;
    bool has_alt_gps_m;
    float alt_gps_m;
    bool has_alt_baro_m;
    float alt_baro_m;
    bool has_speed_ms;
    float speed_ms;
    pb_size_t q_count;
    float q[4];
    bool has_rssi;
    float rssi;
    bool has_snr;
    float snr;
} groundstation_RocketLoRaSample;

typedef PB_BYTES_ARRAY_T(255) groundstation_Lora1Rf69Packet_data_t;
typedef struct _groundstation_Lora1Rf69Packet {
    bool has_data;
    groundstation_Lora1Rf69Packet_data_t data;
    bool has_rssi;
    float rssi;
    bool has_snr;
    float snr;
} groundstation_Lora1Rf69Packet;

typedef struct _groundstation_AntennaState {
    bool has_timestamp;
    uint64_t timestamp;
    bool has_actual_az;
    float actual_az;
    bool has_actual_el;
    float actual_el;
    bool has_target_az;
    float target_az;
    bool has_target_el;
    float target_el;
    bool has_actual_az_mech;
    float actual_az_mech;
    bool has_target_az_mech;
    float target_az_mech;
    bool has_az_calibrated;
    bool az_calibrated;
    bool has_zen_calibrated;
    bool zen_calibrated;
    bool has_tracking_enabled;
    bool tracking_enabled;
    bool has_az_moving;
    bool az_moving;
    bool has_zen_moving;
    bool zen_moving;
    bool has_az_faulted;
    bool az_faulted;
    bool has_zen_faulted;
    bool zen_faulted;
    bool has_mode;
    char mode[16];
    bool has_armed;
    bool armed;
    bool has_gs_fresh;
    bool gs_fresh;
    bool has_target_fresh;
    bool target_fresh;
    bool has_ahrs_el_used;
    bool ahrs_el_used;
    bool has_ahrs_az_used;
    bool ahrs_az_used;
    bool has_distance_m;
    float distance_m;
    bool has_pointing_error_az;
    float pointing_error_az;
    bool has_pointing_error_el;
    float pointing_error_el;
    bool has_az_reference_deg;
    float az_reference_deg;
    bool has_el_reference_deg;
    float el_reference_deg;
    bool has_calibration_seq;
    uint32_t calibration_seq;
    bool has_calibration_status;
    char calibration_status[48];
} groundstation_AntennaState;

typedef struct _groundstation_GroundImu {
    bool has_timestamp;
    uint64_t timestamp;
    bool has_roll;
    float roll;
    bool has_pitch;
    float pitch;
    bool has_yaw;
    float yaw;
    bool has_yaw360;
    float yaw360;
    pb_size_t q_count;
    float q[4];
    pb_size_t a_count;
    float a[3];
    pb_size_t m_count;
    float m[3];
    bool has_have_mag;
    bool have_mag;
    bool has_startup;
    bool startup;
    bool has_mag_rec;
    bool mag_rec;
    bool has_acc_rec;
    bool acc_rec;
    bool has_alt_baro;
    float alt_baro;
    bool has_temp;
    float temp;
    bool has_valid;
    bool valid;
    bool has_have_yaw_frame;
    bool have_yaw_frame;
    bool has_yaw_frame_yaw;
    float yaw_frame_yaw;
    bool has_yaw_frame_yaw360;
    float yaw_frame_yaw360;
    bool has_yaw_startup;
    bool yaw_startup;
    bool has_bar_rel_roll;
    float bar_rel_roll;
    bool has_bar_rel_pitch;
    float bar_rel_pitch;
    bool has_bar_rel_yaw;
    float bar_rel_yaw;
    pb_size_t bar_q_count;
    float bar_q[4]; /* Raw bar/zenith AHRS quaternion q_EB [w,x,y,z] */
    pb_size_t yaw_q_count;
    float yaw_q[4]; /* Raw yaw-platform AHRS quaternion q_EY [w,x,y,z] */
    pb_size_t bar_rel_q_count;
    float bar_rel_q[4]; /* Relative quaternion q_YB = inverse(q_EY) * q_EB [w,x,y,z] */
} groundstation_GroundImu;

typedef struct _groundstation_AhrsStatus {
    bool has_timestamp;
    uint64_t timestamp;
    bool has_running;
    bool running;
    bool has_have_bar_imu;
    bool have_bar_imu;
    bool has_have_bar_mag;
    bool have_bar_mag;
    bool has_have_yaw_imu;
    bool have_yaw_imu;
    bool has_have_yaw_mag;
    bool have_yaw_mag;
    bool has_bar_updates;
    uint32_t bar_updates;
    bool has_yaw_updates;
    uint32_t yaw_updates;
} groundstation_AhrsStatus;

typedef struct _groundstation_RawImuSample {
    bool has_timestamp;
    uint64_t timestamp;
    bool has_ax;
    float ax;
    bool has_ay;
    float ay;
    bool has_az;
    float az;
    bool has_gx;
    float gx;
    bool has_gy;
    float gy;
    bool has_gz;
    float gz;
    bool has_temp;
    float temp;
} groundstation_RawImuSample;

typedef struct _groundstation_RawMagSample {
    bool has_timestamp;
    uint64_t timestamp;
    bool has_mx;
    float mx;
    bool has_my;
    float my;
    bool has_mz;
    float mz;
} groundstation_RawMagSample;

typedef struct _groundstation_RawYawImuSample {
    bool has_timestamp;
    uint64_t timestamp;
    bool has_ax;
    float ax;
    bool has_ay;
    float ay;
    bool has_az;
    float az;
    bool has_gx;
    float gx;
    bool has_gy;
    float gy;
    bool has_gz;
    float gz;
    bool has_mx_ut;
    float mx_ut;
    bool has_my_ut;
    float my_ut;
    bool has_mz_ut;
    float mz_ut;
    bool has_mag_valid;
    bool mag_valid;
    bool has_mag_overflow;
    bool mag_overflow;
    bool has_temp;
    float temp;
} groundstation_RawYawImuSample;

typedef struct _groundstation_RawSensorsCommand {
    bool has_imu;
    bool imu;
    bool has_mag;
    bool mag;
    bool has_yaw_imu;
    bool yaw_imu;
} groundstation_RawSensorsCommand;

typedef struct _groundstation_AxisCommand {
    bool has_target_angle_deg;
    float target_angle_deg;
    bool has_speed_dps;
    float speed_dps;
    bool has_stop;
    bool stop;
    bool has_absolute_ahrs;
    bool absolute_ahrs;
} groundstation_AxisCommand;

typedef struct _groundstation_JogCommand {
    bool has_axis;
    groundstation_JogAxis axis;
    bool has_delta_deg;
    float delta_deg;
    bool has_speed_dps;
    float speed_dps;
} groundstation_JogCommand;

typedef struct _groundstation_DeclinationCommand {
    bool has_declination_deg;
    float declination_deg;
} groundstation_DeclinationCommand;

/* Magnetometer hard/soft-iron calibration for one sensor.  The app fits an
 ellipsoid from raw samples and pushes the result to the Pico, which applies it
 in the AHRS via FusionModelMagnetic before the sensor remap.  hard_iron is the
 ellipsoid centre (µT, sensor native frame); soft_iron is a 3x3 row-major matrix
 that maps the ellipsoid to a sphere. */
typedef struct _groundstation_MagCalibrationCommand {
    bool has_yaw;
    bool yaw; /* true = yaw-platform LIS3MDL, false = bar/zenith LIS3MDL */
    pb_size_t hard_iron_count;
    float hard_iron[3]; /* [hx, hy, hz] */
    pb_size_t soft_iron_count;
    float soft_iron[9]; /* 9 elements, row-major 3x3 */
} groundstation_MagCalibrationCommand;

typedef struct _groundstation_TrackerModeCommand {
    bool has_mode;
    groundstation_TrackerMode mode;
} groundstation_TrackerModeCommand;

typedef struct _groundstation_TrackerArmCommand {
    bool has_armed;
    bool armed;
} groundstation_TrackerArmCommand;

typedef struct _groundstation_TrackerConfigCommand {
    bool has_yaw_trim_deg;
    float yaw_trim_deg;
    bool has_el_trim_deg;
    float el_trim_deg;
    bool has_az_min_deg;
    float az_min_deg;
    bool has_az_max_deg;
    float az_max_deg;
    bool has_el_min_deg;
    float el_min_deg;
    bool has_el_max_deg;
    float el_max_deg;
    bool has_default_speed_dps;
    float default_speed_dps;
    bool has_max_speed_dps;
    float max_speed_dps;
    bool has_scan_speed_az_dps;
    float scan_speed_az_dps;
    bool has_scan_speed_el_dps;
    float scan_speed_el_dps;
    bool has_gs_timeout_ms;
    uint32_t gs_timeout_ms;
    bool has_target_timeout_ms;
    uint32_t target_timeout_ms;
    bool has_distance_min_m;
    float distance_min_m;
    bool has_scan_on_loss;
    bool scan_on_loss;
    bool has_use_ahrs_el;
    bool use_ahrs_el;
    bool has_use_ahrs_az;
    bool use_ahrs_az;
    bool has_ahrs_max_age_ms;
    float ahrs_max_age_ms;
    bool has_ahrs_feedback_gain;
    float ahrs_feedback_gain;
    bool has_ahrs_max_correction_deg;
    float ahrs_max_correction_deg;
} groundstation_TrackerConfigCommand;

typedef struct _groundstation_CalibrationCommand {
    bool has_action;
    groundstation_CalibrationAction action;
    bool has_reference_deg;
    float reference_deg;
    bool has_note;
    char note[96];
    bool has_step;
    uint32_t step;
} groundstation_CalibrationCommand;

typedef struct _groundstation_LocationCommand {
    bool has_lat;
    double lat;
    bool has_lon;
    double lon;
    bool has_alt_m;
    double alt_m;
} groundstation_LocationCommand;

typedef struct _groundstation_StarlinkProxyStatus {
    bool has_lat;
    double lat;
    bool has_lon;
    double lon;
    bool has_alt;
    double alt;
    bool has_horizontal_speed_mps;
    float horizontal_speed_mps;
    bool has_vertical_speed_mps;
    float vertical_speed_mps;
    bool has_pop_ping_latency_ms;
    float pop_ping_latency_ms;
    bool has_pop_ping_drop_rate;
    float pop_ping_drop_rate;
    bool has_downlink_throughput_bps;
    float downlink_throughput_bps;
    bool has_uplink_throughput_bps;
    float uplink_throughput_bps;
    bool has_boresight_azimuth_deg;
    float boresight_azimuth_deg;
    bool has_boresight_elevation_deg;
    float boresight_elevation_deg;
    bool has_gps_valid;
    bool gps_valid;
    bool has_gps_sats;
    uint32_t gps_sats;
    bool has_hardware_version;
    char hardware_version[64];
    bool has_software_version;
    char software_version[64];
    bool has_uptime_s;
    uint32_t uptime_s;
    bool has_error;
    char error[160];
    bool has_location_error;
    char location_error[160];
    bool has_last_ok;
    double last_ok;
} groundstation_StarlinkProxyStatus;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _groundstation_FlightState_MIN groundstation_FlightState_FLIGHT_STATE_GROUND_IDLE
#define _groundstation_FlightState_MAX groundstation_FlightState_FLIGHT_STATE_FAULT
#define _groundstation_FlightState_ARRAYSIZE ((groundstation_FlightState)(groundstation_FlightState_FLIGHT_STATE_FAULT+1))

#define _groundstation_JogAxis_MIN groundstation_JogAxis_JOG_AXIS_UNSPECIFIED
#define _groundstation_JogAxis_MAX groundstation_JogAxis_JOG_AXIS_EL
#define _groundstation_JogAxis_ARRAYSIZE ((groundstation_JogAxis)(groundstation_JogAxis_JOG_AXIS_EL+1))

#define _groundstation_TrackerMode_MIN groundstation_TrackerMode_TRACKER_MODE_STOP
#define _groundstation_TrackerMode_MAX groundstation_TrackerMode_TRACKER_MODE_FAULT
#define _groundstation_TrackerMode_ARRAYSIZE ((groundstation_TrackerMode)(groundstation_TrackerMode_TRACKER_MODE_FAULT+1))

#define _groundstation_CalibrationAction_MIN groundstation_CalibrationAction_CAL_ACTION_UNSPECIFIED
#define _groundstation_CalibrationAction_MAX groundstation_CalibrationAction_CAL_ACTION_ENABLE_TRACKING
#define _groundstation_CalibrationAction_ARRAYSIZE ((groundstation_CalibrationAction)(groundstation_CalibrationAction_CAL_ACTION_ENABLE_TRACKING+1))

#define groundstation_RocketLoRaSample_state_ENUMTYPE groundstation_FlightState










#define groundstation_JogCommand_axis_ENUMTYPE groundstation_JogAxis



#define groundstation_TrackerModeCommand_mode_ENUMTYPE groundstation_TrackerMode



#define groundstation_CalibrationCommand_action_ENUMTYPE groundstation_CalibrationAction




/* Initializer values for message structs */
#define groundstation_RocketLoRaSample_init_default {false, 0, false, _groundstation_FlightState_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, 0, {0, 0, 0, 0}, false, 0, false, 0}
#define groundstation_Lora1Rf69Packet_init_default {false, {0, {0}}, false, 0, false, 0}
#define groundstation_AntennaState_init_default  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, ""}
#define groundstation_GroundImu_init_default     {false, 0, false, 0, false, 0, false, 0, false, 0, 0, {0, 0, 0, 0}, 0, {0, 0, 0}, 0, {0, 0, 0}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}}
#define groundstation_AhrsStatus_init_default    {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define groundstation_RawImuSample_init_default  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define groundstation_RawMagSample_init_default  {false, 0, false, 0, false, 0, false, 0}
#define groundstation_RawYawImuSample_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define groundstation_RawSensorsCommand_init_default {false, 0, false, 0, false, 0}
#define groundstation_AxisCommand_init_default   {false, 0, false, 0, false, 0, false, 0}
#define groundstation_JogCommand_init_default    {false, _groundstation_JogAxis_MIN, false, 0, false, 0}
#define groundstation_DeclinationCommand_init_default {false, 0}
#define groundstation_MagCalibrationCommand_init_default {false, 0, 0, {0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define groundstation_TrackerModeCommand_init_default {false, _groundstation_TrackerMode_MIN}
#define groundstation_TrackerArmCommand_init_default {false, 0}
#define groundstation_TrackerConfigCommand_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define groundstation_CalibrationCommand_init_default {false, _groundstation_CalibrationAction_MIN, false, 0, false, "", false, 0}
#define groundstation_LocationCommand_init_default {false, 0, false, 0, false, 0}
#define groundstation_StarlinkProxyStatus_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, "", false, 0, false, "", false, "", false, 0}
#define groundstation_RocketLoRaSample_init_zero {false, 0, false, _groundstation_FlightState_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, 0, {0, 0, 0, 0}, false, 0, false, 0}
#define groundstation_Lora1Rf69Packet_init_zero  {false, {0, {0}}, false, 0, false, 0}
#define groundstation_AntennaState_init_zero     {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, ""}
#define groundstation_GroundImu_init_zero        {false, 0, false, 0, false, 0, false, 0, false, 0, 0, {0, 0, 0, 0}, 0, {0, 0, 0}, 0, {0, 0, 0}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}}
#define groundstation_AhrsStatus_init_zero       {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define groundstation_RawImuSample_init_zero     {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define groundstation_RawMagSample_init_zero     {false, 0, false, 0, false, 0, false, 0}
#define groundstation_RawYawImuSample_init_zero  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define groundstation_RawSensorsCommand_init_zero {false, 0, false, 0, false, 0}
#define groundstation_AxisCommand_init_zero      {false, 0, false, 0, false, 0, false, 0}
#define groundstation_JogCommand_init_zero       {false, _groundstation_JogAxis_MIN, false, 0, false, 0}
#define groundstation_DeclinationCommand_init_zero {false, 0}
#define groundstation_MagCalibrationCommand_init_zero {false, 0, 0, {0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define groundstation_TrackerModeCommand_init_zero {false, _groundstation_TrackerMode_MIN}
#define groundstation_TrackerArmCommand_init_zero {false, 0}
#define groundstation_TrackerConfigCommand_init_zero {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define groundstation_CalibrationCommand_init_zero {false, _groundstation_CalibrationAction_MIN, false, 0, false, "", false, 0}
#define groundstation_LocationCommand_init_zero  {false, 0, false, 0, false, 0}
#define groundstation_StarlinkProxyStatus_init_zero {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, "", false, 0, false, "", false, "", false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define groundstation_RocketLoRaSample_boot_ms_tag 1
#define groundstation_RocketLoRaSample_state_tag 2
#define groundstation_RocketLoRaSample_sats_tag  3
#define groundstation_RocketLoRaSample_flags_tag 4
#define groundstation_RocketLoRaSample_lat_tag   5
#define groundstation_RocketLoRaSample_lon_tag   6
#define groundstation_RocketLoRaSample_alt_gps_m_tag 7
#define groundstation_RocketLoRaSample_alt_baro_m_tag 8
#define groundstation_RocketLoRaSample_speed_ms_tag 9
#define groundstation_RocketLoRaSample_q_tag     10
#define groundstation_RocketLoRaSample_rssi_tag  11
#define groundstation_RocketLoRaSample_snr_tag   12
#define groundstation_Lora1Rf69Packet_data_tag   1
#define groundstation_Lora1Rf69Packet_rssi_tag   2
#define groundstation_Lora1Rf69Packet_snr_tag    3
#define groundstation_AntennaState_timestamp_tag 1
#define groundstation_AntennaState_actual_az_tag 2
#define groundstation_AntennaState_actual_el_tag 3
#define groundstation_AntennaState_target_az_tag 4
#define groundstation_AntennaState_target_el_tag 5
#define groundstation_AntennaState_actual_az_mech_tag 6
#define groundstation_AntennaState_target_az_mech_tag 7
#define groundstation_AntennaState_az_calibrated_tag 8
#define groundstation_AntennaState_zen_calibrated_tag 9
#define groundstation_AntennaState_tracking_enabled_tag 10
#define groundstation_AntennaState_az_moving_tag 11
#define groundstation_AntennaState_zen_moving_tag 12
#define groundstation_AntennaState_az_faulted_tag 13
#define groundstation_AntennaState_zen_faulted_tag 14
#define groundstation_AntennaState_mode_tag      15
#define groundstation_AntennaState_armed_tag     16
#define groundstation_AntennaState_gs_fresh_tag  17
#define groundstation_AntennaState_target_fresh_tag 18
#define groundstation_AntennaState_ahrs_el_used_tag 19
#define groundstation_AntennaState_ahrs_az_used_tag 20
#define groundstation_AntennaState_distance_m_tag 21
#define groundstation_AntennaState_pointing_error_az_tag 22
#define groundstation_AntennaState_pointing_error_el_tag 23
#define groundstation_AntennaState_az_reference_deg_tag 24
#define groundstation_AntennaState_el_reference_deg_tag 25
#define groundstation_AntennaState_calibration_seq_tag 26
#define groundstation_AntennaState_calibration_status_tag 27
#define groundstation_GroundImu_timestamp_tag    1
#define groundstation_GroundImu_roll_tag         2
#define groundstation_GroundImu_pitch_tag        3
#define groundstation_GroundImu_yaw_tag          4
#define groundstation_GroundImu_yaw360_tag       5
#define groundstation_GroundImu_q_tag            6
#define groundstation_GroundImu_a_tag            7
#define groundstation_GroundImu_m_tag            8
#define groundstation_GroundImu_have_mag_tag     9
#define groundstation_GroundImu_startup_tag      10
#define groundstation_GroundImu_mag_rec_tag      11
#define groundstation_GroundImu_acc_rec_tag      12
#define groundstation_GroundImu_alt_baro_tag     13
#define groundstation_GroundImu_temp_tag         14
#define groundstation_GroundImu_valid_tag        15
#define groundstation_GroundImu_have_yaw_frame_tag 16
#define groundstation_GroundImu_yaw_frame_yaw_tag 17
#define groundstation_GroundImu_yaw_frame_yaw360_tag 18
#define groundstation_GroundImu_yaw_startup_tag  19
#define groundstation_GroundImu_bar_rel_roll_tag 20
#define groundstation_GroundImu_bar_rel_pitch_tag 21
#define groundstation_GroundImu_bar_rel_yaw_tag  22
#define groundstation_GroundImu_bar_q_tag        23
#define groundstation_GroundImu_yaw_q_tag        24
#define groundstation_GroundImu_bar_rel_q_tag    25
#define groundstation_AhrsStatus_timestamp_tag   1
#define groundstation_AhrsStatus_running_tag     2
#define groundstation_AhrsStatus_have_bar_imu_tag 3
#define groundstation_AhrsStatus_have_bar_mag_tag 4
#define groundstation_AhrsStatus_have_yaw_imu_tag 5
#define groundstation_AhrsStatus_have_yaw_mag_tag 6
#define groundstation_AhrsStatus_bar_updates_tag 7
#define groundstation_AhrsStatus_yaw_updates_tag 8
#define groundstation_RawImuSample_timestamp_tag 1
#define groundstation_RawImuSample_ax_tag        2
#define groundstation_RawImuSample_ay_tag        3
#define groundstation_RawImuSample_az_tag        4
#define groundstation_RawImuSample_gx_tag        5
#define groundstation_RawImuSample_gy_tag        6
#define groundstation_RawImuSample_gz_tag        7
#define groundstation_RawImuSample_temp_tag      8
#define groundstation_RawMagSample_timestamp_tag 1
#define groundstation_RawMagSample_mx_tag        2
#define groundstation_RawMagSample_my_tag        3
#define groundstation_RawMagSample_mz_tag        4
#define groundstation_RawYawImuSample_timestamp_tag 1
#define groundstation_RawYawImuSample_ax_tag     2
#define groundstation_RawYawImuSample_ay_tag     3
#define groundstation_RawYawImuSample_az_tag     4
#define groundstation_RawYawImuSample_gx_tag     5
#define groundstation_RawYawImuSample_gy_tag     6
#define groundstation_RawYawImuSample_gz_tag     7
#define groundstation_RawYawImuSample_mx_ut_tag  8
#define groundstation_RawYawImuSample_my_ut_tag  9
#define groundstation_RawYawImuSample_mz_ut_tag  10
#define groundstation_RawYawImuSample_mag_valid_tag 11
#define groundstation_RawYawImuSample_mag_overflow_tag 12
#define groundstation_RawYawImuSample_temp_tag   13
#define groundstation_RawSensorsCommand_imu_tag  1
#define groundstation_RawSensorsCommand_mag_tag  2
#define groundstation_RawSensorsCommand_yaw_imu_tag 3
#define groundstation_AxisCommand_target_angle_deg_tag 1
#define groundstation_AxisCommand_speed_dps_tag  2
#define groundstation_AxisCommand_stop_tag       3
#define groundstation_AxisCommand_absolute_ahrs_tag 4
#define groundstation_JogCommand_axis_tag        1
#define groundstation_JogCommand_delta_deg_tag   2
#define groundstation_JogCommand_speed_dps_tag   3
#define groundstation_DeclinationCommand_declination_deg_tag 1
#define groundstation_MagCalibrationCommand_yaw_tag 1
#define groundstation_MagCalibrationCommand_hard_iron_tag 2
#define groundstation_MagCalibrationCommand_soft_iron_tag 3
#define groundstation_TrackerModeCommand_mode_tag 1
#define groundstation_TrackerArmCommand_armed_tag 1
#define groundstation_TrackerConfigCommand_yaw_trim_deg_tag 1
#define groundstation_TrackerConfigCommand_el_trim_deg_tag 2
#define groundstation_TrackerConfigCommand_az_min_deg_tag 3
#define groundstation_TrackerConfigCommand_az_max_deg_tag 4
#define groundstation_TrackerConfigCommand_el_min_deg_tag 5
#define groundstation_TrackerConfigCommand_el_max_deg_tag 6
#define groundstation_TrackerConfigCommand_default_speed_dps_tag 7
#define groundstation_TrackerConfigCommand_max_speed_dps_tag 8
#define groundstation_TrackerConfigCommand_scan_speed_az_dps_tag 9
#define groundstation_TrackerConfigCommand_scan_speed_el_dps_tag 10
#define groundstation_TrackerConfigCommand_gs_timeout_ms_tag 11
#define groundstation_TrackerConfigCommand_target_timeout_ms_tag 12
#define groundstation_TrackerConfigCommand_distance_min_m_tag 13
#define groundstation_TrackerConfigCommand_scan_on_loss_tag 14
#define groundstation_TrackerConfigCommand_use_ahrs_el_tag 15
#define groundstation_TrackerConfigCommand_use_ahrs_az_tag 16
#define groundstation_TrackerConfigCommand_ahrs_max_age_ms_tag 17
#define groundstation_TrackerConfigCommand_ahrs_feedback_gain_tag 18
#define groundstation_TrackerConfigCommand_ahrs_max_correction_deg_tag 19
#define groundstation_CalibrationCommand_action_tag 1
#define groundstation_CalibrationCommand_reference_deg_tag 2
#define groundstation_CalibrationCommand_note_tag 3
#define groundstation_CalibrationCommand_step_tag 4
#define groundstation_LocationCommand_lat_tag    1
#define groundstation_LocationCommand_lon_tag    2
#define groundstation_LocationCommand_alt_m_tag  3
#define groundstation_StarlinkProxyStatus_lat_tag 1
#define groundstation_StarlinkProxyStatus_lon_tag 2
#define groundstation_StarlinkProxyStatus_alt_tag 3
#define groundstation_StarlinkProxyStatus_horizontal_speed_mps_tag 4
#define groundstation_StarlinkProxyStatus_vertical_speed_mps_tag 5
#define groundstation_StarlinkProxyStatus_pop_ping_latency_ms_tag 6
#define groundstation_StarlinkProxyStatus_pop_ping_drop_rate_tag 7
#define groundstation_StarlinkProxyStatus_downlink_throughput_bps_tag 8
#define groundstation_StarlinkProxyStatus_uplink_throughput_bps_tag 9
#define groundstation_StarlinkProxyStatus_boresight_azimuth_deg_tag 10
#define groundstation_StarlinkProxyStatus_boresight_elevation_deg_tag 11
#define groundstation_StarlinkProxyStatus_gps_valid_tag 12
#define groundstation_StarlinkProxyStatus_gps_sats_tag 13
#define groundstation_StarlinkProxyStatus_hardware_version_tag 14
#define groundstation_StarlinkProxyStatus_software_version_tag 15
#define groundstation_StarlinkProxyStatus_uptime_s_tag 16
#define groundstation_StarlinkProxyStatus_error_tag 17
#define groundstation_StarlinkProxyStatus_location_error_tag 18
#define groundstation_StarlinkProxyStatus_last_ok_tag 19

/* Struct field encoding specification for nanopb */
#define groundstation_RocketLoRaSample_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   boot_ms,           1) \
X(a, STATIC,   OPTIONAL, UENUM,    state,             2) \
X(a, STATIC,   OPTIONAL, UINT32,   sats,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   flags,             4) \
X(a, STATIC,   OPTIONAL, DOUBLE,   lat,               5) \
X(a, STATIC,   OPTIONAL, DOUBLE,   lon,               6) \
X(a, STATIC,   OPTIONAL, FLOAT,    alt_gps_m,         7) \
X(a, STATIC,   OPTIONAL, FLOAT,    alt_baro_m,        8) \
X(a, STATIC,   OPTIONAL, FLOAT,    speed_ms,          9) \
X(a, STATIC,   REPEATED, FLOAT,    q,                10) \
X(a, STATIC,   OPTIONAL, FLOAT,    rssi,             11) \
X(a, STATIC,   OPTIONAL, FLOAT,    snr,              12)
#define groundstation_RocketLoRaSample_CALLBACK NULL
#define groundstation_RocketLoRaSample_DEFAULT NULL

#define groundstation_Lora1Rf69Packet_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BYTES,    data,              1) \
X(a, STATIC,   OPTIONAL, FLOAT,    rssi,              2) \
X(a, STATIC,   OPTIONAL, FLOAT,    snr,               3)
#define groundstation_Lora1Rf69Packet_CALLBACK NULL
#define groundstation_Lora1Rf69Packet_DEFAULT NULL

#define groundstation_AntennaState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         1) \
X(a, STATIC,   OPTIONAL, FLOAT,    actual_az,         2) \
X(a, STATIC,   OPTIONAL, FLOAT,    actual_el,         3) \
X(a, STATIC,   OPTIONAL, FLOAT,    target_az,         4) \
X(a, STATIC,   OPTIONAL, FLOAT,    target_el,         5) \
X(a, STATIC,   OPTIONAL, FLOAT,    actual_az_mech,    6) \
X(a, STATIC,   OPTIONAL, FLOAT,    target_az_mech,    7) \
X(a, STATIC,   OPTIONAL, BOOL,     az_calibrated,     8) \
X(a, STATIC,   OPTIONAL, BOOL,     zen_calibrated,    9) \
X(a, STATIC,   OPTIONAL, BOOL,     tracking_enabled,  10) \
X(a, STATIC,   OPTIONAL, BOOL,     az_moving,        11) \
X(a, STATIC,   OPTIONAL, BOOL,     zen_moving,       12) \
X(a, STATIC,   OPTIONAL, BOOL,     az_faulted,       13) \
X(a, STATIC,   OPTIONAL, BOOL,     zen_faulted,      14) \
X(a, STATIC,   OPTIONAL, STRING,   mode,             15) \
X(a, STATIC,   OPTIONAL, BOOL,     armed,            16) \
X(a, STATIC,   OPTIONAL, BOOL,     gs_fresh,         17) \
X(a, STATIC,   OPTIONAL, BOOL,     target_fresh,     18) \
X(a, STATIC,   OPTIONAL, BOOL,     ahrs_el_used,     19) \
X(a, STATIC,   OPTIONAL, BOOL,     ahrs_az_used,     20) \
X(a, STATIC,   OPTIONAL, FLOAT,    distance_m,       21) \
X(a, STATIC,   OPTIONAL, FLOAT,    pointing_error_az,  22) \
X(a, STATIC,   OPTIONAL, FLOAT,    pointing_error_el,  23) \
X(a, STATIC,   OPTIONAL, FLOAT,    az_reference_deg,  24) \
X(a, STATIC,   OPTIONAL, FLOAT,    el_reference_deg,  25) \
X(a, STATIC,   OPTIONAL, UINT32,   calibration_seq,  26) \
X(a, STATIC,   OPTIONAL, STRING,   calibration_status,  27)
#define groundstation_AntennaState_CALLBACK NULL
#define groundstation_AntennaState_DEFAULT NULL

#define groundstation_GroundImu_FIELDLIST(X, a_) \
X(a_, STATIC,   OPTIONAL, UINT64,   timestamp,         1) \
X(a_, STATIC,   OPTIONAL, FLOAT,    roll,              2) \
X(a_, STATIC,   OPTIONAL, FLOAT,    pitch,             3) \
X(a_, STATIC,   OPTIONAL, FLOAT,    yaw,               4) \
X(a_, STATIC,   OPTIONAL, FLOAT,    yaw360,            5) \
X(a_, STATIC,   REPEATED, FLOAT,    q,                 6) \
X(a_, STATIC,   REPEATED, FLOAT,    a,                 7) \
X(a_, STATIC,   REPEATED, FLOAT,    m,                 8) \
X(a_, STATIC,   OPTIONAL, BOOL,     have_mag,          9) \
X(a_, STATIC,   OPTIONAL, BOOL,     startup,          10) \
X(a_, STATIC,   OPTIONAL, BOOL,     mag_rec,          11) \
X(a_, STATIC,   OPTIONAL, BOOL,     acc_rec,          12) \
X(a_, STATIC,   OPTIONAL, FLOAT,    alt_baro,         13) \
X(a_, STATIC,   OPTIONAL, FLOAT,    temp,             14) \
X(a_, STATIC,   OPTIONAL, BOOL,     valid,            15) \
X(a_, STATIC,   OPTIONAL, BOOL,     have_yaw_frame,   16) \
X(a_, STATIC,   OPTIONAL, FLOAT,    yaw_frame_yaw,    17) \
X(a_, STATIC,   OPTIONAL, FLOAT,    yaw_frame_yaw360,  18) \
X(a_, STATIC,   OPTIONAL, BOOL,     yaw_startup,      19) \
X(a_, STATIC,   OPTIONAL, FLOAT,    bar_rel_roll,     20) \
X(a_, STATIC,   OPTIONAL, FLOAT,    bar_rel_pitch,    21) \
X(a_, STATIC,   OPTIONAL, FLOAT,    bar_rel_yaw,      22) \
X(a_, STATIC,   REPEATED, FLOAT,    bar_q,            23) \
X(a_, STATIC,   REPEATED, FLOAT,    yaw_q,            24) \
X(a_, STATIC,   REPEATED, FLOAT,    bar_rel_q,        25)
#define groundstation_GroundImu_CALLBACK NULL
#define groundstation_GroundImu_DEFAULT NULL

#define groundstation_AhrsStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         1) \
X(a, STATIC,   OPTIONAL, BOOL,     running,           2) \
X(a, STATIC,   OPTIONAL, BOOL,     have_bar_imu,      3) \
X(a, STATIC,   OPTIONAL, BOOL,     have_bar_mag,      4) \
X(a, STATIC,   OPTIONAL, BOOL,     have_yaw_imu,      5) \
X(a, STATIC,   OPTIONAL, BOOL,     have_yaw_mag,      6) \
X(a, STATIC,   OPTIONAL, UINT32,   bar_updates,       7) \
X(a, STATIC,   OPTIONAL, UINT32,   yaw_updates,       8)
#define groundstation_AhrsStatus_CALLBACK NULL
#define groundstation_AhrsStatus_DEFAULT NULL

#define groundstation_RawImuSample_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         1) \
X(a, STATIC,   OPTIONAL, FLOAT,    ax,                2) \
X(a, STATIC,   OPTIONAL, FLOAT,    ay,                3) \
X(a, STATIC,   OPTIONAL, FLOAT,    az,                4) \
X(a, STATIC,   OPTIONAL, FLOAT,    gx,                5) \
X(a, STATIC,   OPTIONAL, FLOAT,    gy,                6) \
X(a, STATIC,   OPTIONAL, FLOAT,    gz,                7) \
X(a, STATIC,   OPTIONAL, FLOAT,    temp,              8)
#define groundstation_RawImuSample_CALLBACK NULL
#define groundstation_RawImuSample_DEFAULT NULL

#define groundstation_RawMagSample_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         1) \
X(a, STATIC,   OPTIONAL, FLOAT,    mx,                2) \
X(a, STATIC,   OPTIONAL, FLOAT,    my,                3) \
X(a, STATIC,   OPTIONAL, FLOAT,    mz,                4)
#define groundstation_RawMagSample_CALLBACK NULL
#define groundstation_RawMagSample_DEFAULT NULL

#define groundstation_RawYawImuSample_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         1) \
X(a, STATIC,   OPTIONAL, FLOAT,    ax,                2) \
X(a, STATIC,   OPTIONAL, FLOAT,    ay,                3) \
X(a, STATIC,   OPTIONAL, FLOAT,    az,                4) \
X(a, STATIC,   OPTIONAL, FLOAT,    gx,                5) \
X(a, STATIC,   OPTIONAL, FLOAT,    gy,                6) \
X(a, STATIC,   OPTIONAL, FLOAT,    gz,                7) \
X(a, STATIC,   OPTIONAL, FLOAT,    mx_ut,             8) \
X(a, STATIC,   OPTIONAL, FLOAT,    my_ut,             9) \
X(a, STATIC,   OPTIONAL, FLOAT,    mz_ut,            10) \
X(a, STATIC,   OPTIONAL, BOOL,     mag_valid,        11) \
X(a, STATIC,   OPTIONAL, BOOL,     mag_overflow,     12) \
X(a, STATIC,   OPTIONAL, FLOAT,    temp,             13)
#define groundstation_RawYawImuSample_CALLBACK NULL
#define groundstation_RawYawImuSample_DEFAULT NULL

#define groundstation_RawSensorsCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     imu,               1) \
X(a, STATIC,   OPTIONAL, BOOL,     mag,               2) \
X(a, STATIC,   OPTIONAL, BOOL,     yaw_imu,           3)
#define groundstation_RawSensorsCommand_CALLBACK NULL
#define groundstation_RawSensorsCommand_DEFAULT NULL

#define groundstation_AxisCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    target_angle_deg,   1) \
X(a, STATIC,   OPTIONAL, FLOAT,    speed_dps,         2) \
X(a, STATIC,   OPTIONAL, BOOL,     stop,              3) \
X(a, STATIC,   OPTIONAL, BOOL,     absolute_ahrs,     4)
#define groundstation_AxisCommand_CALLBACK NULL
#define groundstation_AxisCommand_DEFAULT NULL

#define groundstation_JogCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    axis,              1) \
X(a, STATIC,   OPTIONAL, FLOAT,    delta_deg,         2) \
X(a, STATIC,   OPTIONAL, FLOAT,    speed_dps,         3)
#define groundstation_JogCommand_CALLBACK NULL
#define groundstation_JogCommand_DEFAULT NULL

#define groundstation_DeclinationCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    declination_deg,   1)
#define groundstation_DeclinationCommand_CALLBACK NULL
#define groundstation_DeclinationCommand_DEFAULT NULL

#define groundstation_MagCalibrationCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     yaw,               1) \
X(a, STATIC,   REPEATED, FLOAT,    hard_iron,         2) \
X(a, STATIC,   REPEATED, FLOAT,    soft_iron,         3)
#define groundstation_MagCalibrationCommand_CALLBACK NULL
#define groundstation_MagCalibrationCommand_DEFAULT NULL

#define groundstation_TrackerModeCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    mode,              1)
#define groundstation_TrackerModeCommand_CALLBACK NULL
#define groundstation_TrackerModeCommand_DEFAULT NULL

#define groundstation_TrackerArmCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     armed,             1)
#define groundstation_TrackerArmCommand_CALLBACK NULL
#define groundstation_TrackerArmCommand_DEFAULT NULL

#define groundstation_TrackerConfigCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    yaw_trim_deg,      1) \
X(a, STATIC,   OPTIONAL, FLOAT,    el_trim_deg,       2) \
X(a, STATIC,   OPTIONAL, FLOAT,    az_min_deg,        3) \
X(a, STATIC,   OPTIONAL, FLOAT,    az_max_deg,        4) \
X(a, STATIC,   OPTIONAL, FLOAT,    el_min_deg,        5) \
X(a, STATIC,   OPTIONAL, FLOAT,    el_max_deg,        6) \
X(a, STATIC,   OPTIONAL, FLOAT,    default_speed_dps,   7) \
X(a, STATIC,   OPTIONAL, FLOAT,    max_speed_dps,     8) \
X(a, STATIC,   OPTIONAL, FLOAT,    scan_speed_az_dps,   9) \
X(a, STATIC,   OPTIONAL, FLOAT,    scan_speed_el_dps,  10) \
X(a, STATIC,   OPTIONAL, UINT32,   gs_timeout_ms,    11) \
X(a, STATIC,   OPTIONAL, UINT32,   target_timeout_ms,  12) \
X(a, STATIC,   OPTIONAL, FLOAT,    distance_min_m,   13) \
X(a, STATIC,   OPTIONAL, BOOL,     scan_on_loss,     14) \
X(a, STATIC,   OPTIONAL, BOOL,     use_ahrs_el,      15) \
X(a, STATIC,   OPTIONAL, BOOL,     use_ahrs_az,      16) \
X(a, STATIC,   OPTIONAL, FLOAT,    ahrs_max_age_ms,  17) \
X(a, STATIC,   OPTIONAL, FLOAT,    ahrs_feedback_gain,  18) \
X(a, STATIC,   OPTIONAL, FLOAT,    ahrs_max_correction_deg,  19)
#define groundstation_TrackerConfigCommand_CALLBACK NULL
#define groundstation_TrackerConfigCommand_DEFAULT NULL

#define groundstation_CalibrationCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    action,            1) \
X(a, STATIC,   OPTIONAL, FLOAT,    reference_deg,     2) \
X(a, STATIC,   OPTIONAL, STRING,   note,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   step,              4)
#define groundstation_CalibrationCommand_CALLBACK NULL
#define groundstation_CalibrationCommand_DEFAULT NULL

#define groundstation_LocationCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, DOUBLE,   lat,               1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   lon,               2) \
X(a, STATIC,   OPTIONAL, DOUBLE,   alt_m,             3)
#define groundstation_LocationCommand_CALLBACK NULL
#define groundstation_LocationCommand_DEFAULT NULL

#define groundstation_StarlinkProxyStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, DOUBLE,   lat,               1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   lon,               2) \
X(a, STATIC,   OPTIONAL, DOUBLE,   alt,               3) \
X(a, STATIC,   OPTIONAL, FLOAT,    horizontal_speed_mps,   4) \
X(a, STATIC,   OPTIONAL, FLOAT,    vertical_speed_mps,   5) \
X(a, STATIC,   OPTIONAL, FLOAT,    pop_ping_latency_ms,   6) \
X(a, STATIC,   OPTIONAL, FLOAT,    pop_ping_drop_rate,   7) \
X(a, STATIC,   OPTIONAL, FLOAT,    downlink_throughput_bps,   8) \
X(a, STATIC,   OPTIONAL, FLOAT,    uplink_throughput_bps,   9) \
X(a, STATIC,   OPTIONAL, FLOAT,    boresight_azimuth_deg,  10) \
X(a, STATIC,   OPTIONAL, FLOAT,    boresight_elevation_deg,  11) \
X(a, STATIC,   OPTIONAL, BOOL,     gps_valid,        12) \
X(a, STATIC,   OPTIONAL, UINT32,   gps_sats,         13) \
X(a, STATIC,   OPTIONAL, STRING,   hardware_version,  14) \
X(a, STATIC,   OPTIONAL, STRING,   software_version,  15) \
X(a, STATIC,   OPTIONAL, UINT32,   uptime_s,         16) \
X(a, STATIC,   OPTIONAL, STRING,   error,            17) \
X(a, STATIC,   OPTIONAL, STRING,   location_error,   18) \
X(a, STATIC,   OPTIONAL, DOUBLE,   last_ok,          19)
#define groundstation_StarlinkProxyStatus_CALLBACK NULL
#define groundstation_StarlinkProxyStatus_DEFAULT NULL

extern const pb_msgdesc_t groundstation_RocketLoRaSample_msg;
extern const pb_msgdesc_t groundstation_Lora1Rf69Packet_msg;
extern const pb_msgdesc_t groundstation_AntennaState_msg;
extern const pb_msgdesc_t groundstation_GroundImu_msg;
extern const pb_msgdesc_t groundstation_AhrsStatus_msg;
extern const pb_msgdesc_t groundstation_RawImuSample_msg;
extern const pb_msgdesc_t groundstation_RawMagSample_msg;
extern const pb_msgdesc_t groundstation_RawYawImuSample_msg;
extern const pb_msgdesc_t groundstation_RawSensorsCommand_msg;
extern const pb_msgdesc_t groundstation_AxisCommand_msg;
extern const pb_msgdesc_t groundstation_JogCommand_msg;
extern const pb_msgdesc_t groundstation_DeclinationCommand_msg;
extern const pb_msgdesc_t groundstation_MagCalibrationCommand_msg;
extern const pb_msgdesc_t groundstation_TrackerModeCommand_msg;
extern const pb_msgdesc_t groundstation_TrackerArmCommand_msg;
extern const pb_msgdesc_t groundstation_TrackerConfigCommand_msg;
extern const pb_msgdesc_t groundstation_CalibrationCommand_msg;
extern const pb_msgdesc_t groundstation_LocationCommand_msg;
extern const pb_msgdesc_t groundstation_StarlinkProxyStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define groundstation_RocketLoRaSample_fields &groundstation_RocketLoRaSample_msg
#define groundstation_Lora1Rf69Packet_fields &groundstation_Lora1Rf69Packet_msg
#define groundstation_AntennaState_fields &groundstation_AntennaState_msg
#define groundstation_GroundImu_fields &groundstation_GroundImu_msg
#define groundstation_AhrsStatus_fields &groundstation_AhrsStatus_msg
#define groundstation_RawImuSample_fields &groundstation_RawImuSample_msg
#define groundstation_RawMagSample_fields &groundstation_RawMagSample_msg
#define groundstation_RawYawImuSample_fields &groundstation_RawYawImuSample_msg
#define groundstation_RawSensorsCommand_fields &groundstation_RawSensorsCommand_msg
#define groundstation_AxisCommand_fields &groundstation_AxisCommand_msg
#define groundstation_JogCommand_fields &groundstation_JogCommand_msg
#define groundstation_DeclinationCommand_fields &groundstation_DeclinationCommand_msg
#define groundstation_MagCalibrationCommand_fields &groundstation_MagCalibrationCommand_msg
#define groundstation_TrackerModeCommand_fields &groundstation_TrackerModeCommand_msg
#define groundstation_TrackerArmCommand_fields &groundstation_TrackerArmCommand_msg
#define groundstation_TrackerConfigCommand_fields &groundstation_TrackerConfigCommand_msg
#define groundstation_CalibrationCommand_fields &groundstation_CalibrationCommand_msg
#define groundstation_LocationCommand_fields &groundstation_LocationCommand_msg
#define groundstation_StarlinkProxyStatus_fields &groundstation_StarlinkProxyStatus_msg

/* Maximum encoded size of messages (where known) */
#define GROUNDSTATION_GROUND_STATION_PB_H_MAX_SIZE groundstation_StarlinkProxyStatus_size
#define groundstation_AhrsStatus_size            33
#define groundstation_AntennaState_size          174
#define groundstation_AxisCommand_size           14
#define groundstation_CalibrationCommand_size    110
#define groundstation_DeclinationCommand_size    5
#define groundstation_GroundImu_size             209
#define groundstation_JogCommand_size            12
#define groundstation_LocationCommand_size       27
#define groundstation_Lora1Rf69Packet_size       268
#define groundstation_MagCalibrationCommand_size 62
#define groundstation_RawImuSample_size          46
#define groundstation_RawMagSample_size          26
#define groundstation_RawSensorsCommand_size     6
#define groundstation_RawYawImuSample_size       65
#define groundstation_RocketLoRaSample_size      84
#define groundstation_StarlinkProxyStatus_size   548
#define groundstation_TrackerArmCommand_size     2
#define groundstation_TrackerConfigCommand_size  92
#define groundstation_TrackerModeCommand_size    2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
