# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spacex_api/telemetron/public/integrations/rate_limit_reason.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spacex_api/telemetron/public/integrations/rate_limit_reason.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAspacex_api/telemetron/public/integrations/rate_limit_reason.proto\x12)SpaceX.API.Telemetron.Public.Integrations*\x84\x01\n\x0fRateLimitReason\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08NO_LIMIT\x10\x01\x12\x10\n\x0cPOLICY_LIMIT\x10\x02\x12\x15\n\x11USER_CUSTOM_LIMIT\x10\x03\x12\x11\n\rOVERAGE_LIMIT\x10\x05\x12\x1a\n\x16LOW_SPEED_POLICY_LIMIT\x10\x06\x42?Z=spacex.com/api/telemetron/public/integrations/ratelimitreasonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacex_api.telemetron.public.integrations.rate_limit_reason_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=spacex.com/api/telemetron/public/integrations/ratelimitreason'
  _globals['_RATELIMITREASON']._serialized_start=113
  _globals['_RATELIMITREASON']._serialized_end=245
# @@protoc_insertion_point(module_scope)
